In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/airqualityuci/AirQualityUCI.csv


In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("/kaggle/input/airqualityuci/AirQualityUCI.csv")
data

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10-03-2004  18:00:00     2.6       1360.0     150.0      11.9   
1     10-03-2004  19:00:00     2.0       1292.0     112.0       9.4   
2     10-03-2004  20:00:00     2.2       1402.0      88.0       9.0   
3     10-03-2004  21:00:00     2.2       1376.0      80.0       9.2   
4     10-03-2004  22:00:00     1.6       1272.0      51.0       6.5   
...          ...       ...     ...          ...       ...       ...   
9466         NaN       NaN     NaN          NaN       NaN       NaN   
9467         NaN       NaN     NaN          NaN       NaN       NaN   
9468         NaN       NaN     NaN          NaN       NaN       NaN   
9469         NaN       NaN     NaN          NaN       NaN       NaN   
9470         NaN       NaN     NaN          NaN       NaN       NaN   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9466            NaN      NaN           NaN      NaN           NaN   
9467            NaN      NaN           NaN      NaN           NaN   
9468            NaN      NaN           NaN      NaN           NaN   
9469            NaN      NaN           NaN      NaN           NaN   
9470            NaN      NaN           NaN      NaN           NaN   

      PT08.S5(O3)     T    RH      AH  Unnamed: 15  Unnamed: 16  
0          1268.0  13.6  48.9  0.7578          NaN          NaN  
1           972.0  13.3  47.7  0.7255          NaN          NaN  
2          1074.0  11.9  54.0  0.7502          NaN          NaN  
3          1203.0  11.0  60.0  0.7867          NaN          NaN  
4          1110.0  11.2  59.6  0.7888          NaN          NaN  
...           ...   ...   ...     ...          ...          ...  
9466          NaN   NaN   NaN     NaN          NaN          NaN  
9467          NaN   NaN   NaN     NaN          NaN          NaN  
9468          NaN   NaN   NaN     NaN          NaN          NaN  
9469          NaN   NaN   NaN     NaN          NaN          NaN  
9470          NaN   NaN   NaN     NaN          NaN          NaN  

[9471 rows x 17 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(15), object(2)
memory usage: 1.2+ MB


In [5]:
data.isnull().sum()

Date              114
Time              114
CO(GT)            114
PT08.S1(CO)       114
NMHC(GT)          114
C6H6(GT)          114
PT08.S2(NMHC)     114
NOx(GT)           114
PT08.S3(NOx)      114
NO2(GT)           114
PT08.S4(NO2)      114
PT08.S5(O3)       114
T                 114
RH                114
AH                114
Unnamed: 15      9471
Unnamed: 16      9471
dtype: int64

In [6]:
dataset=data.fillna(1000)

In [7]:
dataset

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10-03-2004  18:00:00     2.6       1360.0     150.0      11.9   
1     10-03-2004  19:00:00     2.0       1292.0     112.0       9.4   
2     10-03-2004  20:00:00     2.2       1402.0      88.0       9.0   
3     10-03-2004  21:00:00     2.2       1376.0      80.0       9.2   
4     10-03-2004  22:00:00     1.6       1272.0      51.0       6.5   
...          ...       ...     ...          ...       ...       ...   
9466        1000      1000  1000.0       1000.0    1000.0    1000.0   
9467        1000      1000  1000.0       1000.0    1000.0    1000.0   
9468        1000      1000  1000.0       1000.0    1000.0    1000.0   
9469        1000      1000  1000.0       1000.0    1000.0    1000.0   
9470        1000      1000  1000.0       1000.0    1000.0    1000.0   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0            1046.0    166.0        1056.0    113.0        1692.0   
1             955.0    103.0        1174.0     92.0        1559.0   
2             939.0    131.0        1140.0    114.0        1555.0   
3             948.0    172.0        1092.0    122.0        1584.0   
4             836.0    131.0        1205.0    116.0        1490.0   
...             ...      ...           ...      ...           ...   
9466         1000.0   1000.0        1000.0   1000.0        1000.0   
9467         1000.0   1000.0        1000.0   1000.0        1000.0   
9468         1000.0   1000.0        1000.0   1000.0        1000.0   
9469         1000.0   1000.0        1000.0   1000.0        1000.0   
9470         1000.0   1000.0        1000.0   1000.0        1000.0   

      PT08.S5(O3)       T      RH         AH  Unnamed: 15  Unnamed: 16  
0          1268.0    13.6    48.9     0.7578       1000.0       1000.0  
1           972.0    13.3    47.7     0.7255       1000.0       1000.0  
2          1074.0    11.9    54.0     0.7502       1000.0       1000.0  
3          1203.0    11.0    60.0     0.7867       1000.0       1000.0  
4          1110.0    11.2    59.6     0.7888       1000.0       1000.0  
...           ...     ...     ...        ...          ...          ...  
9466       1000.0  1000.0  1000.0  1000.0000       1000.0       1000.0  
9467       1000.0  1000.0  1000.0  1000.0000       1000.0       1000.0  
9468       1000.0  1000.0  1000.0  1000.0000       1000.0       1000.0  
9469       1000.0  1000.0  1000.0  1000.0000       1000.0       1000.0  
9470       1000.0  1000.0  1000.0  1000.0000       1000.0       1000.0  

[9471 rows x 17 columns]

In [8]:
dataset.isnull().any()

Date             False
Time             False
CO(GT)           False
PT08.S1(CO)      False
NMHC(GT)         False
C6H6(GT)         False
PT08.S2(NMHC)    False
NOx(GT)          False
PT08.S3(NOx)     False
NO2(GT)          False
PT08.S4(NO2)     False
PT08.S5(O3)      False
T                False
RH               False
AH               False
Unnamed: 15      False
Unnamed: 16      False
dtype: bool

In [9]:
x=dataset.iloc[:,[2,3,4,5,6,7,8,9,10,11,12,13]].values
x

array([[   2.6, 1360. ,  150. , ..., 1268. ,   13.6,   48.9],
       [   2. , 1292. ,  112. , ...,  972. ,   13.3,   47.7],
       [   2.2, 1402. ,   88. , ..., 1074. ,   11.9,   54. ],
       ...,
       [1000. , 1000. , 1000. , ..., 1000. , 1000. , 1000. ],
       [1000. , 1000. , 1000. , ..., 1000. , 1000. , 1000. ],
       [1000. , 1000. , 1000. , ..., 1000. , 1000. , 1000. ]])

In [10]:
y=dataset.iloc[:,-3].values
y

array([7.578e-01, 7.255e-01, 7.502e-01, ..., 1.000e+03, 1.000e+03,
       1.000e+03])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=9)


In [12]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)


LinearRegression()

In [13]:
y_pred=l1.predict(x_test)
print(y_pred)

[ 2.07400812  0.38512352  2.02920165 ...  0.99119018 -0.30889684
  2.75937241]


In [14]:
x_test

array([[ 9.000e-01,  8.830e+02, -2.000e+02, ...,  7.100e+02,  9.500e+00,
         6.990e+01],
       [ 2.200e+00,  1.183e+03, -2.000e+02, ...,  1.186e+03,  1.020e+01,
         6.150e+01],
       [ 1.300e+00,  1.069e+03, -2.000e+02, ...,  9.760e+02,  1.930e+01,
         7.160e+01],
       ...,
       [-2.000e+02,  1.138e+03, -2.000e+02, ...,  1.947e+03,  2.730e+01,
         3.430e+01],
       [-2.000e+02,  1.296e+03, -2.000e+02, ...,  7.460e+02,  2.610e+01,
         3.080e+01],
       [ 2.300e+00,  1.078e+03, -2.000e+02, ...,  1.013e+03,  4.060e+01,
         1.530e+01]])

In [15]:
y_test

array([0.8298, 0.7638, 1.5844, ..., 1.2284, 1.0253, 1.1485])

In [16]:
print("TreaningAccuracy",l1.score(x_train,y_train))

TreaningAccuracy 0.9999129474391473


In [17]:
print("TestingAccuracy",l1.score(x_test,y_pred))

TestingAccuracy 1.0


In [18]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred)*100)

99.9916649952306
