In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv


# Import Libaries

In [2]:
import pandas as pd
import numpy as np

# Load Train dataset

In [3]:
dataset=pd.read_csv("/kaggle/input/spaceship-titanic/train.csv")
dataset

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [5]:
dataset.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

# Slicing Train dataset

In [6]:
x=dataset.iloc[:,:-1]
x

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy  
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines  
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent  
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent  
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines  
...           ...        ...           ...     ...     ...                ...  
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther  
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley  
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon  
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre  
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre  

[8693 rows x 13 columns]

# Converting string data

In [7]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()

In [8]:
for D1 in dataset.columns:
    if dataset[D1].dtype == object:
        dataset[D1] = dataset[D1].astype(str)
        X1=dataset[D1].unique()
        X2=X1[-2]
        
        dataset[D1]=dataset[D1].fillna(X2)
        dataset[D1]=l1.fit_transform(dataset[D1])
    elif dataset[D1].dtype == float or dataset[D1].dtype == int:
        m1=dataset[D1].mean()
        m1=round(m1)
        dataset[D1]=dataset[D1].fillna(m1)
        
print(dataset)

      PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           1          0    149            2  39.0    0   
1               1           0          0   2184            2  24.0    0   
2               2           1          0      1            2  58.0    1   
3               3           1          0      1            2  33.0    0   
4               4           0          0   2186            2  16.0    0   
...           ...         ...        ...    ...          ...   ...  ...   
8688         8688           1          0    146            0  41.0    1   
8689         8689           0          1   5280            1  18.0    0   
8690         8690           0          0   5285            2  26.0    0   
8691         8691           1          0   2131            0  32.0    0   
8692         8692           1          0   2131            2  44.0    0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name  Transported  
0             0.0  

In [9]:
del dataset["Transported"]

In [10]:
dataset

PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           1          0    149            2  39.0    0   
1               1           0          0   2184            2  24.0    0   
2               2           1          0      1            2  58.0    1   
3               3           1          0      1            2  33.0    0   
4               4           0          0   2186            2  16.0    0   
...           ...         ...        ...    ...          ...   ...  ...   
8688         8688           1          0    146            0  41.0    1   
8689         8689           0          1   5280            1  18.0    0   
8690         8690           0          0   5285            2  26.0    0   
8691         8691           1          0   2131            0  32.0    0   
8692         8692           1          0   2131            2  44.0    0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name  
0             0.0        0.0           0.0     0.0     0.0  5252  
1           109.0        9.0          25.0   549.0    44.0  4502  
2            43.0     3576.0           0.0  6715.0    49.0   457  
3             0.0     1283.0         371.0  3329.0   193.0  7149  
4           303.0       70.0         151.0   565.0     2.0  8319  
...           ...        ...           ...     ...     ...   ...  
8688          0.0     6819.0           0.0  1643.0    74.0  3524  
8689          0.0        0.0           0.0     0.0     0.0  4780  
8690          0.0        0.0        1872.0     1.0     0.0  3002  
8691          0.0     1049.0           0.0   353.0  3235.0  1596  
8692        126.0     4688.0           0.0     0.0    12.0  6380  

[8693 rows x 13 columns]

# Load Test data

In [11]:
data=pd.read_csv("/kaggle/input/spaceship-titanic/test.csv")
data

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False   
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False   
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False   
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False   
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False   
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False   
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False   
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False   
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0             0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1             0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2             0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3             0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4            10.0        0.0         635.0     0.0     0.0   Brence Harperez  
...           ...        ...           ...     ...     ...               ...  
4272          0.0        0.0           0.0     0.0     0.0       Jeron Peter  
4273          0.0      847.0          17.0    10.0   144.0     Matty Scheron  
4274          0.0        0.0           0.0     0.0     0.0       Jayrin Pore  
4275          0.0     2680.0           0.0     0.0   523.0    Kitakan Conale  
4276          0.0        0.0           0.0     0.0     0.0  Lilace Leonzaley  

[4277 rows x 13 columns]

# Converting string data

In [12]:
for D1 in data.columns:
    if data[D1].dtype == object:
        data[D1] = data[D1].astype(str)
        X1=data[D1].unique()
        X2=X1[-2]
        
        data[D1]=data[D1].fillna(X2)
        data[D1]=l1.fit_transform(data[D1])
    elif data[D1].dtype == float or data[D1].dtype == int:
        m1=data[D1].mean()
        m1=round(m1)
        data[D1]=data[D1].fillna(m1)
        
print(data)

      PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           0          1   2784            2  27.0    0   
1               1           0          0   1867            2  19.0    0   
2               2           1          1    257            0  31.0    0   
3               3           1          0    259            2  38.0    0   
4               4           0          0   1940            2  20.0    0   
...           ...         ...        ...    ...          ...   ...  ...   
4272         4272           0          1   2679            2  34.0    0   
4273         4273           0          0   3265            2  42.0    0   
4274         4274           2          1    602            0  29.0    0   
4275         4275           1          0    603            3  29.0    0   
4276         4276           0          1   2680            1  43.0    0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name  
0             0.0        0.0    

In [13]:
data

PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0               0           0          1   2784            2  27.0    0   
1               1           0          0   1867            2  19.0    0   
2               2           1          1    257            0  31.0    0   
3               3           1          0    259            2  38.0    0   
4               4           0          0   1940            2  20.0    0   
...           ...         ...        ...    ...          ...   ...  ...   
4272         4272           0          1   2679            2  34.0    0   
4273         4273           0          0   3265            2  42.0    0   
4274         4274           2          1    602            0  29.0    0   
4275         4275           1          0    603            3  29.0    0   
4276         4276           0          1   2680            1  43.0    0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Name  
0             0.0        0.0           0.0     0.0     0.0  2912  
1             0.0        9.0           0.0  2823.0     0.0  2406  
2             0.0        0.0           0.0     0.0     0.0  3376  
3             0.0     6652.0           0.0   181.0   585.0  2711  
4            10.0        0.0         635.0     0.0     0.0   668  
...           ...        ...           ...     ...     ...   ...  
4272          0.0        0.0           0.0     0.0     0.0  2105  
4273          0.0      847.0          17.0    10.0   144.0  2654  
4274          0.0        0.0           0.0     0.0     0.0  2085  
4275          0.0     2680.0           0.0     0.0   523.0  2327  
4276          0.0        0.0           0.0     0.0     0.0  2439  

[4277 rows x 13 columns]

In [14]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   int64  
 1   HomePlanet    8693 non-null   int64  
 2   CryoSleep     8693 non-null   int64  
 3   Cabin         8693 non-null   int64  
 4   Destination   8693 non-null   int64  
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   int64  
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   int64  
dtypes: float64(6), int64(7)
memory usage: 883.0 KB


In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   4277 non-null   int64  
 1   HomePlanet    4277 non-null   int64  
 2   CryoSleep     4277 non-null   int64  
 3   Cabin         4277 non-null   int64  
 4   Destination   4277 non-null   int64  
 5   Age           4277 non-null   float64
 6   VIP           4277 non-null   int64  
 7   RoomService   4277 non-null   float64
 8   FoodCourt     4277 non-null   float64
 9   ShoppingMall  4277 non-null   float64
 10  Spa           4277 non-null   float64
 11  VRDeck        4277 non-null   float64
 12  Name          4277 non-null   int64  
dtypes: float64(6), int64(7)
memory usage: 434.5 KB


# Loading Training dataset

In [16]:
dataset1=pd.read_csv("/kaggle/input/spaceship-titanic/train.csv")
dataset1

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [17]:
from sklearn.preprocessing import LabelEncoder
l2=LabelEncoder()
dataset1["Transported"]=l2.fit_transform(dataset1["Transported"])

# Data Preprocessing

In [18]:
dataset1["Transported"]

0       0
1       1
2       0
3       0
4       1
       ..
8688    0
8689    0
8690    1
8691    0
8692    1
Name: Transported, Length: 8693, dtype: int64

# Data Slicing

In [19]:
x=dataset.iloc[:,:].values
y=dataset1.iloc[:,-1].values

In [20]:
x

array([[0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.252e+03],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 5.490e+02, 4.400e+01,
        4.502e+03],
       [2.000e+00, 1.000e+00, 0.000e+00, ..., 6.715e+03, 4.900e+01,
        4.570e+02],
       ...,
       [8.690e+03, 0.000e+00, 0.000e+00, ..., 1.000e+00, 0.000e+00,
        3.002e+03],
       [8.691e+03, 1.000e+00, 0.000e+00, ..., 3.530e+02, 3.235e+03,
        1.596e+03],
       [8.692e+03, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.200e+01,
        6.380e+03]])

In [21]:
y

array([0, 1, 0, ..., 1, 0, 1])

In [22]:
data1=dataset.iloc[:,:].values

# Using Standard Scaler

In [23]:
from sklearn.preprocessing import StandardScaler
s1=StandardScaler()
x=s1.fit_transform(x)
data1=s1.fit_transform(data1)

In [24]:
data.shape

(4277, 13)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=9)

# Using Logistic regression

In [26]:
from sklearn.linear_model import LogisticRegression 
l3=LogisticRegression()
l3.fit(x_train,y_train)

LogisticRegression()

In [27]:
y_pred=l3.predict(x_test)
y_pred

array([0, 0, 1, ..., 1, 1, 1])

In [28]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)*100
ac

76.65324899367452

# SVM Support Vector Machine

In [29]:
from sklearn.svm import SVC
svc1=SVC(kernel='linear',random_state=11)
svc1.fit(x_train,y_train)

SVC(kernel='linear', random_state=11)

In [30]:
y_pred1=svc1.predict(x_test)
y_pred1

array([0, 0, 1, ..., 1, 1, 1])

In [31]:
from sklearn.metrics import accuracy_score
ac1=accuracy_score(y_test,y_pred1)*100
print(ac1)

78.26336975273146


In [32]:
from sklearn.svm import SVC
svc2=SVC(kernel='linear',random_state=11)
svc2.fit(x,y)

SVC(kernel='linear', random_state=11)

In [33]:
y_pred_3=svc2.predict(data)
y_pred_3

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but SVC was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


array([0, 0, 0, ..., 1, 1, 0])

In [34]:
end=[]
for x in y_pred_3:
    if x==0:
        end.append(False)
    else:
        end.append(True)

In [35]:
end1=pd.read_csv(r"/kaggle/input/spaceship-titanic/test.csv")
end1.insert(1,"Transported",end)
end2=end1.iloc[:,[0,1]]
end2

PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01         True
4        0023_01         True
...          ...          ...
4272     9266_02        False
4273     9269_01         True
4274     9271_01         True
4275     9273_01         True
4276     9277_01        False

[4277 rows x 2 columns]

In [36]:
import os
end2.to_csv(r'sample_submission.csv',index=False)


from IPython.display import FileLink
FileLink(r'sample_submission.csv')

/kaggle/working/sample_submission.csv