In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/red-wine-quality-cortez-et-al-2009/winequality-red.csv


In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("/kaggle/input/red-wine-quality-cortez-et-al-2009/winequality-red.csv")

In [4]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [6]:
data.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [7]:
x=data.iloc[:,[1,2,3,4,5,6,7,8,9,10,11]].values
x

array([[ 0.7  ,  0.   ,  1.9  , ...,  0.56 ,  9.4  ,  5.   ],
       [ 0.88 ,  0.   ,  2.6  , ...,  0.68 ,  9.8  ,  5.   ],
       [ 0.76 ,  0.04 ,  2.3  , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 0.51 ,  0.13 ,  2.3  , ...,  0.75 , 11.   ,  6.   ],
       [ 0.645,  0.12 ,  2.   , ...,  0.71 , 10.2  ,  5.   ],
       [ 0.31 ,  0.47 ,  3.6  , ...,  0.66 , 11.   ,  6.   ]])

In [8]:
y=data.iloc[:,-1].values
y

array([5, 5, 5, ..., 6, 5, 6])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=9)

In [10]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred=l1.predict(x_test)
print(y_pred)

[6. 6. 5. 6. 6. 6. 4. 6. 5. 5. 6. 7. 5. 5. 5. 7. 5. 5. 6. 3. 6. 6. 6. 5.
 6. 6. 7. 5. 6. 6. 6. 6. 6. 6. 8. 5. 6. 4. 5. 5. 5. 8. 5. 5. 5. 6. 5. 5.
 6. 5. 5. 5. 7. 7. 6. 7. 5. 6. 6. 6. 5. 6. 5. 5. 6. 5. 5. 5. 7. 5. 4. 7.
 4. 6. 5. 5. 5. 6. 7. 5. 5. 5. 6. 7. 5. 5. 6. 7. 5. 5. 6. 6. 5. 5. 7. 6.
 6. 6. 6. 5. 5. 7. 6. 6. 7. 6. 6. 6. 5. 6. 6. 5. 6. 5. 5. 6. 6. 5. 6. 5.
 5. 6. 6. 5. 6. 6. 5. 6. 5. 7. 5. 6. 5. 6. 5. 6. 6. 6. 5. 5. 5. 5. 6. 5.
 6. 6. 6. 6. 6. 5. 5. 6. 6. 5. 7. 5. 5. 6. 5. 6. 6. 6. 7. 6. 6. 5. 5. 6.
 6. 6. 6. 5. 6. 6. 7. 7. 6. 5. 6. 5. 5. 5. 5. 6. 6. 6. 7. 6. 6. 6. 5. 6.
 6. 6. 5. 5. 5. 5. 7. 7. 5. 5. 5. 5. 5. 6. 5. 6. 7. 5. 6. 7. 5. 5. 4. 5.
 5. 5. 5. 6. 6. 6. 5. 6. 5. 5. 5. 6. 7. 5. 6. 7. 5. 6. 5. 5. 6. 4. 7. 7.
 6. 6. 5. 3. 5. 6. 4. 5. 7. 6. 5. 5. 5. 6. 6. 7. 5. 6. 5. 7. 6. 5. 6. 6.
 6. 6. 6. 7. 5. 5. 5. 7. 6. 7. 5. 5. 5. 6. 5. 5. 5. 5. 5. 6. 5. 6. 6. 7.
 5. 6. 6. 5. 5. 6. 5. 7. 5. 6. 5. 5. 5. 6. 5. 5. 4. 5. 5. 5. 5. 5. 5. 5.
 6. 6. 6. 5. 5. 5. 5. 6.]


In [12]:
x_test

array([[ 0.35,  0.6 ,  2.6 , ...,  0.79, 11.1 ,  6.  ],
       [ 0.59,  0.5 ,  2.  , ...,  1.61,  9.5 ,  6.  ],
       [ 0.61,  0.14,  2.4 , ...,  0.59,  9.5 ,  5.  ],
       ...,
       [ 0.56,  0.09,  2.9 , ...,  0.61, 10.2 ,  5.  ],
       [ 0.69,  0.22,  1.9 , ...,  0.48,  9.5 ,  5.  ],
       [ 0.7 ,  0.  ,  1.7 , ...,  0.53, 10.  ,  6.  ]])

In [13]:
y_train

array([6, 5, 5, ..., 7, 6, 6])

In [14]:
x_train

array([[ 0.39 ,  0.33 ,  3.3  , ...,  0.62 , 12.2  ,  6.   ],
       [ 0.38 ,  0.38 ,  1.6  , ...,  0.65 ,  8.5  ,  5.   ],
       [ 0.5  ,  0.5  , 13.8  , ...,  0.75 ,  8.8  ,  5.   ],
       ...,
       [ 0.915,  0.12 ,  2.2  , ...,  0.65 , 10.2  ,  7.   ],
       [ 0.56 ,  0.31 ,  2.8  , ...,  0.92 , 10.   ,  6.   ],
       [ 0.26 ,  0.42 ,  2.   , ...,  0.8  ,  9.4  ,  6.   ]])

In [15]:
print("TreaningAccuracy",l1.score(x_train,y_train))

TreaningAccuracy 1.0


In [16]:
print("TestingAccuracy",l1.score(x_test,y_pred))

TestingAccuracy 1.0


In [17]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred)*100)

100.0
